In [52]:
import numpy as np

## Практическое задание 3

Все задания рекомендуется делать вручную, затем проверяя полученные результаты с использованием numpy.

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;

произведение неопределено, так как число стоблцов матрицы $A$ не равно числу строк матрицы $B$

б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;

произведение определено, так как число стоблцов матрицы $A$ равно числу строк матрицы $B$. Размерность полученной матрицы $2\times 3$

в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;

произведение определено, так как число стоблцов матрицы $A$ равно числу строк матрицы $B$. Размерность полученной матрицы $8\times 8$

г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

произведение определено, так как число стоблцов матрицы $A$ равно числу строк матрицы $B$. Размерность полученной матрицы $4\times 4$

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

$$\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}+\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}=\begin{pmatrix}
1+4 & -2-1\\ 
3+0 & 0+5
\end{pmatrix}=\begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}$$

In [3]:
A = np.array([[1, -2], 
              [3, 0]])
B = np.array([[4, -1], 
              [0, 5]])
A+B

array([[ 5, -3],
       [ 3,  5]])

$$\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}\cdot\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}=\begin{pmatrix}
1\cdot4+(-2)\cdot0 & 1\cdot(-1)+(-2)\cdot5\\ 
3\cdot4+0\cdot0 & 3\cdot(-1)+0\cdot5
\end{pmatrix}=\begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}$$

In [5]:
A@B

array([[  4, -11],
       [ 12,  -3]])

 __3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$$\begin{pmatrix}
3\cdot1+(-2)\cdot0+4\cdot2 & 3\cdot7+(-2)\cdot5+4\cdot(-4)\\ 
3\cdot3+(-2)\cdot2+4\cdot1 & 3\cdot(-6)+(-2)\cdot(-1)+4\cdot1
\end{pmatrix}=\begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}
$$

In [12]:
A = np.array([[1, 7], 
              [3, -6]])
B = np.array([[0, 5], 
              [2, -1]])
C = np.array([[2, -4], 
              [1, 1]])
3*A-2*B+4*C

array([[ 11,  -5],
       [  9, -12]])

__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

$$A^{T}=\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3\\
\end{pmatrix}$$

$$\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}\cdot\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3\\
\end{pmatrix}=\begin{pmatrix}
4\cdot4+1\cdot1 & 4\cdot5+1\cdot(-2) & 4\cdot2+1\cdot3\\ 
5\cdot4+(-2)\cdot1 & 5\cdot5+(-2)\cdot(-2) & 5\cdot2+(-2)\cdot3\\
2\cdot4+3\cdot1 & 2\cdot5+3\cdot(-2) & 2\cdot2+3\cdot3\\
\end{pmatrix}=\begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\
11 & 4 & 13\\
\end{pmatrix}$$

In [14]:
A = np.array([[4, 1], 
              [5, -2], 
              [2, 3]])
A@A.T

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

$$\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3\\
\end{pmatrix}\cdot\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}=\begin{pmatrix}
4\cdot4+5\cdot5+2\cdot2 & 4\cdot1+5\cdot(-2)+2\cdot3\\ 
1\cdot4+(-2)\cdot5+3\cdot2 & 1\cdot1+(-2)\cdot(-2)+3\cdot3\\
\end{pmatrix}=\begin{pmatrix}
45 & 0\\ 
0 & 14\\
\end{pmatrix}$$

In [15]:
A.T@A

array([[45,  0],
       [ 0, 14]])

__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [37]:
def prod(A, B):
    shape_A=A.shape
    shape_B=B.shape
    if shape_A[1] != shape_B[0]:
        print('произведение матриц неопределено!')
        return
    
    C = []
    for i in range(shape_A[0]):        
        C_row = []
        for k in range(shape_B[1]):
            spam = 0
            for j in range(shape_A[1]):
                spam += A[i][j] * B[j][k]
            C_row.append(spam)
        C.append(C_row)
    return C

In [42]:
print(prod(A.T, A))

[[45, 0], [0, 14]]


## Практическое задание 4

Все задания рекомендуется выполнять вручную, затем проверяя полученные результаты с использованием Numpy.

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix}=
sin^{2}x+cos^{2}x=1$$

In [57]:
x = 1
np.linalg.det([[np.sin(x), -np.cos(x)], 
               [np.cos(x), np.sin(x)]])

1.0

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$

разложим матрицу по первому столбцу:
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix}=4\cdot(-1)^{(1+1)}\cdot\begin{vmatrix}
5 & 1 \\
0 & 9 \\
\end{vmatrix}=4\cdot(5\cdot9-1\cdot0)=180$$

In [59]:
np.linalg.det([[4, 2, 3],
               [0, 5, 1],
               [0, 0, 9]])

180.0

   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

Так как при прибавлении к строке другой строки, умноженной на число, определитель не меняется, мы можем осуществить некоторые преобразования для обнуления максимального количества элементов:

- преобразуем третью строку, вычтя из второй, умноженной на 2, первую.

Получим:

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}=\begin{vmatrix}
0 & 0 & 0\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}=0\cdot(-1)^{(1+1)}\cdot\begin{vmatrix}
5 & 6 \\
8 & 9 \\
\end{vmatrix}+0\cdot(-1)^{(1+2)}\cdot\begin{vmatrix}
4 & 6 \\
7 & 9 \\
\end{vmatrix}+0\cdot(-1)^{(1+3)}\cdot\begin{vmatrix}
4 & 5 \\
7 & 8 \\
\end{vmatrix}=0
$$

In [60]:
np.linalg.det([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])

-9.51619735392994e-16

__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$; используя свойство определителя получим, что $det(A\cdot A)=det(A)\cdot det(A)=16$
    
   б) $det(A^{T})$; используя свойство определителя получим, что $det(A^{T})=det(A)=4$
    
   в) $det(2A)$. используя свойство определителя получим, что $det(2\cdot A)=8$

__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

матрица вырожденная, если ее определитель равен 0
Так как при прибавлении к строке другой строки, умноженной на число, определитель не меняется, мы можем осуществить некоторые преобразования для обнуления максимального количества элементов:

- преобразуем вторую строку, прибавив к ней первую, умноженную на 2.

Получим:
$\begin{pmatrix}
-2 & 7 & -3\\ 
0 & 0 & 0\\ 
-3 & 7 & 13
\end{pmatrix}$
$$\begin{vmatrix}
-2 & 7 & -3\\ 
0 & 0 & 0\\ 
-3 & 7 & 13
\end{vmatrix}=0\cdot(-1)^{(1+1)}\cdot\begin{vmatrix}
7 & -3 \\
7 & 13 \\
\end{vmatrix}+0\cdot(-1)^{(1+2)}\cdot\begin{vmatrix}
-2 & -3 \\
-3 & 13 \\
\end{vmatrix}+0\cdot(-1)^{(1+3)}\cdot\begin{vmatrix}
-2 & 7 \\
-3 & 7 \\
\end{vmatrix}=0
$$

In [61]:
np.linalg.det([[-2, 7, -3],
               [4, -14, 6],
               [-3, 7, 13]])

0.0

__4.__ Найти ранг матрицы:

 а)  $ \begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$
третья строка является суммой первой и второй, ее можно отбросить:
$$\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1
\end{pmatrix}$$
теперь все строки и стоблцы линейно независимы, то есть ранг матрицы равен 2

In [62]:
np.linalg.matrix_rank([[1, 2, 3],
                       [1, 1, 1],
                       [2, 3, 4]])

2

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$ Третья строка является суммой первой и второй, ее можно отбросить:
$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
2 & 3 & 5 & 6
\end{pmatrix}$ теперь все строки и столбцы линейнонезависимы, то есть ранг матрицы равен 3

In [63]:
np.linalg.matrix_rank([[0, 0, 2, 1],
                       [0, 0, 2, 2],
                       [0, 0, 4, 3],
                       [2, 3, 5, 6]])

3